// js-test - JavaScript Entry Point
// Generated by engx create

const config = {
  name: "js-test",
  version: "1.0.0"
};

function main() {
  console.log('Starting application:', config.name);
  console.log('This is a simulated JavaScript project');
}

// Export for testing
module.exports = { main, config };

// Run if this is the main module
if (require.main === module) {
  main();
}
